### ISSUE TITLE
Can't get this to work

### ISSUE THREAD

**Issue by digimadgirl** [masaccio/ha-kingspan-watchman-sensit#1]
I have added the integration with HACS but when I try to 'Add Integration' and select 'Kingspan Connect Sensor Integration for Home Assistant' I get the following error:-

Error
Config flow could not be loaded: {"message":"Invalid handler specified"}

**Comment by masaccio** [comment]
I appreciate the testing but it's still very much in development. You should have seen this message during installation:

https://github.com/masaccio/ha-kingspan-connect-sensor/blob/main/Info.md

Once I have it working I'll let you know on this issue. It will probably take this month as this is my first integration so I am learning as I go.

**Comment by digimadgirl** [comment]
Sorry - I didn't realise it was still in development and I didn't see that message.  I was just excited when I saw it as I have just had a new oil tank and had one of these sensors fitted.  I'll keep a watch on this.  Thank you for working on this and good luck as it's your first integration.  Hopefully one day I might be able to progress to something like this but I've very much just a user at the moment.

**Comment by masaccio** [comment]
@digimadgirl 

Still early days but I have something that's starting to work. Currently it's a custom repository here:

https://github.com/masaccio/ha-kingspan-watchman-sensit

You will need to add HACS to your HA installation if you don't have it already and then add the repository above as per https://hacs.xyz/docs/faq/custom_repositories/

You should then be able to add the entities from the sensor. Currently it's the oil level, the capacity and tank percentage. I need to reformat the percentage and I also want to add a reading date.

As soon as the HA team has accepted my commits then the custom repository should not be necessary.

Let me know how you get on!

**Comment by masaccio** [comment]
New bug: the update doesn't happen after 24 hours.

**Comment by digimadgirl** [comment]
Hi,

Thanks for messaging me.  It isn't quite working for me yet, but I'm happy
to keep testing it.  I've attached some screenshots in case it helps.

Regards,
Michelle

**Comment by masaccio** [comment]
Can you enable debug logs. You will need to edit the `configuration.yaml` file and add this:

``` yaml
logger:
  default: warning
  logs:
    custom_components.kingspan_watchman_sensit: debug
    tplink: debug
```

on restart you should see log entries for this integration. I could not see the attachment BTW

**Comment by masaccio** [comment]
Splendid thanks!
