### ISSUE TITLE
Integration setup fails for new device with no data readings

### ISSUE THREAD

**Issue by radiohe4d** [masaccio/ha-kingspan-watchman-sensit#14]
Whilst trying to setup the integration I get the following error:

![2023-12-02 14_21_30-Home Assistant - Settings – Home Assistant](https://github.com/masaccio/ha-kingspan-watchman-sensit/assets/19432504/14b75267-9db2-4118-b376-303c706691a4)

And the logs show this:

![2023-12-02 14_19_56-Home Assistant - Settings – Home Assistant](https://github.com/masaccio/ha-kingspan-watchman-sensit/assets/19432504/a943c5cd-9a03-4622-b047-c5a7be11b36d)

I have just bought and installed the Watchman Sensit, so It doesn't have any data on the official Kingspan Connect app yet. 

Is it expected that the integration wont allow setup until that data is available?

**Home Assistant Versions:**
Core 2023.11.3
Supervisor 2023.11.6

**ha-kingspan-watchman-sensit version:**
v1.6.2

**Comment by masaccio** [comment]
Did you manage to log in with HA once there was a reading?

**Comment by radiohe4d** [comment]
Yes, worked perfectly after it got its first reading.

**Comment by masaccio** [comment]
Cheers. I'll leave this open and add a test at some point so that the error is clearer.

**Comment by masaccio** [comment]
Fixed in v.1.6.3.
