### ISSUE TITLE
Usage reports as negative after an oil delivery that is considered 'too small'

### ISSUE THREAD

**Issue by alexchatwin** [masaccio/ha-kingspan-watchman-sensit#15]
![image](https://github.com/masaccio/ha-kingspan-watchman-sensit/assets/22892404/78f38e58-4170-4dee-bc26-e5a37e7e4bdb)
This may well be user error!

Is it known than the integration will report negative oil usage in the days after a top-up?

**Comment by masaccio** [comment]
It should ignore deltas where the oil goes up by 25% or more. Was your fill smaller than that?

**Comment by alexchatwin** [comment]
ahh, yes, only 500l in a 2.5k tank

**Comment by masaccio** [comment]
500 litres is quite a lot - maybe I should lower the threshold. It was to catch fluctuations in the levels due to temperature variations, but 25% is excessive. One for my list of things to do.

**Comment by masaccio** [comment]
Fixed in v.1.6.3.
