### ISSUE TITLE
Unsupported state class

### ISSUE THREAD

**Issue by Sooty70** [masaccio/ha-kingspan-watchman-sensit#17]
Hi, Just looking at the Statistics view in the Developer tools and noticed this.

![image](https://github.com/masaccio/ha-kingspan-watchman-sensit/assets/48683879/bfd2274f-adc4-435c-b780-980bca68b927)

Here is the window when you press fix...

![image](https://github.com/masaccio/ha-kingspan-watchman-sensit/assets/48683879/0bdb8321-5443-4f6b-8cb2-6805feb49af5)

I can't think of two many use cases where you would want to track stats on the size of the tank, but it would be nice to get rid of this error from the statistics view!

**Comment by masaccio** [comment]
Fixed in v.1.6.3.
