### ISSUE TITLE
Worked perfectly for months until the upgrade 2 weeks ago

### ISSUE THREAD

**Issue by kirsty99999** [masaccio/ha-kingspan-watchman-sensit#25]
Hi, I am a reasonable novice with Home Assistant. I installed HACS and the Kingspan integration in about August 2023 and it worked perfectly untik 2 weeks ago when it was updated. I am not getting any clues as to what is wrong. It just says 'failed set up, will retry'. Its done this for two weeks. I have updated and restarted HA hoping htat might help. 
When I hover over the message I see 'Error while connecting to device [IP Address]  Call connect failed  (IP Address) (connection error).
Any advice to trouble shoot would be appreciated.
Also, if anyone could tell me what this device shows as on the wireless network that could be usefull. I have a lot of equipement conected and cant see any IP on my router that looks like Kingspan or Sensit.
The Kingsapn app is working perfectly so its not that. I has been updating as usual every morning.
Many thanks! Kirsty

**Comment by Sooty70** [comment]
Did you update to the latest version?  The integration needed some updates following HA release 2024.1.

Also, nothing obvious for you to look for on your LAN for the Kingspan device.  When I first installed it I trapped its MAC & IP and called it 'Oil Sensor' on my Router.  MAC starts 94-B9-7E - sometimes these can be common from the manufacturer.

**Comment by kirsty99999** [comment]
> Did you update to the latest version? The integration needed some updates following HA release 2024.1.
> 
> Also, nothing obvious for you to look for on your LAN for the Kingspan device. When I first installed it I trapped its MAC & IP and called it 'Oil Sensor' on my Router. MAC starts 94-B9-7E - sometimes these can be common from the manufacturer.

Many thanks for your help. I had updated HA but not the Kingspan updates and its working again now! I wanted to idetify it on my network to fix the IP address as I've done with some other things as I thought something like a dynamic IP address may have been the issue. I took a look and have nothing like your MAC address, so I guess I'll just leave for now and fix whenever I work out which of the obscure devices it is. Thanks once again.
