### ISSUE TITLE
Current usage suddenly reporting 10x higher

### ISSUE THREAD

**Issue by m90att** [masaccio/ha-kingspan-watchman-sensit#26]
I've been using the add-on for about 6 months with no issues apart from a lost connection earlier this month.
On 6 Mar 24 Current usage jumped from 5.3l to 51l and has remained in this range ever since.
Consumption has not changed and current usage in the Kingspan app supports this.
It seems that all of a sudden the value is being multiplied by 10 appearing to be since the lost connection.

See screenshots.

![image](https://github.com/masaccio/ha-kingspan-watchman-sensit/assets/56609577/93b8dc99-b0a1-4f20-b41b-cd1c519a3158)

![image](https://github.com/masaccio/ha-kingspan-watchman-sensit/assets/56609577/fc5e1369-0782-4fcd-8536-3a68e0e3c9e7)

![image](https://github.com/masaccio/ha-kingspan-watchman-sensit/assets/56609577/fec414e3-2975-4255-8696-aca0bbc39568)

**Comment by masaccio** [comment]
I had a similar outage and I can only think it's a glitch on the Kingspan side
