### ISSUE TITLE
Is this integration still working?

### ISSUE THREAD

**Issue by RossCC** [masaccio/ha-kingspan-watchman-sensit#27]
I just got a couple of Sensit devices and sensors, but on installing the HA integration, the prompt for username and password always fails.

From what I can see, the connectsensor.com site you are connecting too is meant for another system (Watchman Anywhere Pro). My Kingspan Connect mobile app credentials do not work on this site, however, interestingly I could do a password reset, and the password generated worked on the app, but not at connectsensor.com.

I am wondering have Kingspan blocked connections unless you have the paid subscription for the Anywhere Pro device?

Would be great to get it working, so any advice appreciated.

**Comment by RossCC** [comment]
Amazon Alexa integration is working OK, which I think uses the same server / credentials...

**Comment by masaccio** [comment]
Yes working with latest HA Core.

**Comment by RossCC** [comment]
OK - Interesting development as I still couldn't get it to recognise my username and password.  I have two tanks, one of which has not "Phoned home" yet.  Out of curiosity I removed the 2nd tank from the account, and then the integration will accept my username and password.  

Not sure if this glitch is the result of having two tanks or maybe one tank which hasn't connected yet, but maybe this will help some future people.

**Comment by hilburn** [comment]
Ross Cc 
The latter seems to be the case - I have a single tank that hasn't reported in yet and can't connect in HA

**Comment by masaccio** [comment]
@hilburn you should enable debug to see what is in the logs

**Comment by hilburn** [comment]
I wasn't able to even add the integration because of the bug so wasn't able to enable debug logging - just got the message "invalid username/password"
And this morning it finally registered and I added the integration no problem. TBH I would just add a note to the readme about that rather than stress about fixing it
