### ISSUE TITLE
Detected that custom integration 'kingspan_watchman_sensit' calls `async_add_job`, which is deprecated and will be removed in Home Assistant 2025.4

### ISSUE THREAD

**Issue by paulski999** [masaccio/ha-kingspan-watchman-sensit#28]
Hi, after upgrading Home Assistant Core to 2024.4.2 I noticed that the following error appears in my logs - 

hass[1165]: 2024-04-08 18:34:43.825 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'kingspan_watchman_sensit' calls `async_add_job`, which is deprecated and will be removed in Home Assistant 2025.4; Please review https://developers.home-assistant.io/blog/2024/03/13/deprecate_add_run_job for replacement options at custom_components/kingspan_watchman_sensit/__init__.py, line 81: hass.async_add_job(hass.config_entries.async_forward_entry_setup(entry, platform)), please create a bug report at https://github.com/masaccio/ha-kingspan-watchman-sensit/issues

Would it be possible to look at this issue?
Many thanks again for your assistance

**Comment by masaccio** [comment]
Changed in v1.6.5
