### ISSUE TITLE
precede each entity with a common name.

### ISSUE THREAD

**Issue by RedNo7** [masaccio/ha-kingspan-watchman-sensit#35]
Hi,

Most integrations typically have a `sensor.<integration_name>_tank_percentage_full` format.

Can we have `integration_name` set to the name we gave our tank? So for me, this might be:
`sensor.garden_tank_percentage_full` for example or perhaps `sensor.watchman_garden_tank_percentage_full` which would make it easy to find/use the entities?

**Comment by masaccio** [comment]
It’s a good idea thought it’s a significant change as it could break automations for people who already have the current names. The integration would need to only construct new names on first use or non reconfiguration.

**Comment by RedNo7** [comment]
Agh, fair enough - I’ll change mine manually.

Thanks!
