### ISSUE TITLE
Setup failed for custom integration kingspan_watchman_sensit: Requirements for kingspan_watchman_sensit not found: ['kingspan-connect-sensor==2.1.0'].

### ISSUE THREAD

**Issue by jasonmadigan** [masaccio/ha-kingspan-watchman-sensit#4]
`Setup failed for custom integration kingspan_watchman_sensit: Requirements for kingspan_watchman_sensit not found: ['kingspan-connect-sensor==2.1.0'].`

New error at startup with HA 2023.5

**Comment by prowebuk** [comment]
+1 Same issue

**Comment by masaccio** [comment]
I just updated to latest HA core and it's some new python dependencies that I need to fix. Expect an update in the next couple of days.

**Comment by prowebuk** [comment]
Many tanks for your speedy fix @masaccio
