### ISSUE TITLE
Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

### ISSUE THREAD

**Issue by rupertbriggs** [masaccio/ha-kingspan-watchman-sensit#5]
Hello Please can you help , new to HA , had it working well for a couple of weeks and I think after update it stopped working, I deleted then re added it and now I just get the following - 
Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

**Comment by rupertbriggs** [comment]
I also have this in the log -

Unable to install package kingspan-connect-sensor==2.1.1: ERROR: Cannot install kingspan-connect-sensor==2.1.1 because these package versions have conflicting dependencies.

**Comment by masaccio** [comment]
What version of HA Core are you running? The most recent tests run with 2023.5.1.

**Comment by rupertbriggs** [comment]
that's sorted it ! I just updated the core to 2023.5.3 and I can now log in thanks for your help
