### ISSUE TITLE
Possible Timezone issue? 

### ISSUE THREAD

**Issue by CaptInsano** [masaccio/ha-kingspan-watchman-sensit#7]
The value for Last Reading Date is one hour later in Homeassistant than in the Kingspan App.

The timezone setting in my Homeassistant OS VM is correct.

Reported at 11:28am in app:

![Screenshot_20230624-210255](https://github.com/masaccio/ha-kingspan-watchman-sensit/assets/332478/f80df5f5-97e6-43b3-ab5c-5a1a069d4ebd)

Reported as 12:28pm in Homeassistant:

![Screenshot_20230624-210329](https://github.com/masaccio/ha-kingspan-watchman-sensit/assets/332478/ab59c7c8-6e1c-4853-b794-c876229f1de2)

Timezone settings:

![Screenshot_20230624-210513](https://github.com/masaccio/ha-kingspan-watchman-sensit/assets/332478/2780ff40-f080-435b-82a1-bc37e215308d)

Any idea why this is happening?

Thanks a million for your work on this.

**Comment by masaccio** [comment]
I believe this is fixed now if you update in HACS.
