### ISSUE TITLE
Polling rate/time suggested improvement 

### ISSUE THREAD

**Issue by tombadog99** [masaccio/ha-kingspan-watchman-sensit#8]
Just installed this integration and it's working perfectly - many thanks for the time and effort. 
Just one suggested improvement - would it be possible to either double the polling rate or provide an option to schedule the time of polling as I am finding myself reloading the integration to get an update as there is about an 8 hour gap between the Kingspan app is updating to my HA data updating. It isn't really a big deal but while the device is new and I'm checking it more often, it would be good to not have to refresh the integration manually.

**Comment by masaccio** [comment]
It's a good request, but given a quick look I couldn't see a way of doing it without a change for everyone. Ideally I'd have an options flow where you could just edit the parameter inside the HA GUI. I'll leave this open and look to add in the future.

**Comment by masaccio** [comment]
There's a new options flow now so you can configure the integration and set this. Possibly too late given you have a couple of week data, but a v1.5.0 update in HACS will get it you.

**Comment by tombadog99** [comment]
Thanks for the update! Great job!
